country_tips = {
    "SE": "Visit Stockholm!",
    "ES": "Go watch a Real Madrid game!",
    "IT": "All roads lead to rome!",
    "PT": "Don't miss Porto's wine!",
    "UK": "Go see Big Ben!",
    "FR": "Enjoy the Eiffel Tower!",
    "GR": "Home of Greek mythology",
    "JP": "The home of Anime",
    "KR": "Home of Korean pop",
    "IN": "The Taj Mahal is a must see!",
    "AE": "See the mesmerizing Burj Khalifa!",
    "TR": "The Hagia Sophia",
    "EG": " The Pyramids of Giza",
    "MA": "Go visit Casablanca",
    "ZA": "Go Visit Nelson mandela's home country!",
    "KE": "Go see the safaris just outside Nairobi",
    "US": "Home of the empire state building",
    "CA": "Ottawa, Toronto or Montreal many cities to pick from",
    "BR": "Home of Christ the redeemer statue",
    "AR": "Make sure to go visit Lionel Messi's home country!",
    "FI": "This country is known for thousands of lakes and saunas.",
    "DE": "Join Oktoberfest or visit Berlin’s historical sites.",
    "CN": "Walk along the Great Wall and explore Beijing’s wonders.",
    "RU": "Visit Red Square and the colorful Saint Basil’s Cathedral.",
    "AU": "Dive into the Great Barrier Reef or see kangaroos up close.",
    "MX": "Enjoy tacos, mariachi music, and ancient Mayan pyramids.",
    "NL": "See the tulips, windmills, and canals in Amsterdam.",
    "SA": "Experience desert landscapes and the city of Mecca.",
    "CH": "Explore the Alps and taste world-famous Swiss chocolate.",
    "NO": "See the fjords and Northern Lights in this stunning country.",
    "DK": "Cycle around Copenhagen and experience hygge culture.",
    "PL": "Explore medieval cities like Kraków and hearty local cuisine.",
    "TH": "Try incredible street food and relax on tropical beaches.",
    "VN": "Cruise Ha Long Bay and enjoy a bowl of pho.",
    "PH": "Discover thousands of islands with crystal-clear waters.",
    "ID": "Relax in Bali and explore the world's largest archipelago.",
    "MY": "Climb Petronas Towers and enjoy delicious street food.",
    "SG": "A clean and modern city-state with high fines.",
    "IL": "Walk through Jerusalem and float in the Dead Sea.",
    "IR": "Discover ancient Persian architecture and poetic heritage.",
    "PK": "Admire the mighty Karakoram mountains.",
    "BD": "Visit the rivers, markets, and rich textile culture.",
    "UA": "Explore historic Kyiv and sunflower-covered fields.",
    "CZ": "Visit Prague’s old town and fairytale castles.",
    "HU": "Relax in Budapest’s thermal baths by the Danube.",
    "AT": "Enjoy classical music and the beautiful Alps.",
    "BE": "Taste waffles, chocolate, and medieval charm.",
    "IE": "Discover green hills and ancient Celtic folklore.",
    "NG": "Experience Nollywood and vibrant African culture."
}