# FI: This country is known for thousands of lakes and saunas.
# US: The Statue of Liberty is located here.
# JP: Sushi and cherry blossoms are famous here.
# DE: Oktoberfest is a famous beer festival held here.

country_tips = {
    "FI": "This country is known for thousands of lakes and saunas.",
    "US": "The Statue of Liberty is located here.",
    "JP": "Sushi and cherry blossoms are famous here.",
    "DE": "Oktoberfest is a famous beer festival held here.",
    "CN": "The Great Wall runs across this vast country.",
    "IN": "The Taj Mahal is a world-famous landmark here.",
    "BR": "The Amazon rainforest and Carnival call this place home.",
    "RU": "Known for the Red Square and vast Siberian lands.",
    "FR": "The Eiffel Tower stands tall in its capital.",
    "GB": "Home of Big Ben and afternoon tea.",
    "IT": "Pizza, pasta, and ancient Roman ruins thrive here.",
    "CA": "Niagara Falls and maple syrup are well-known icons here.",
    "AU": "Kangaroos and the Great Barrier Reef are found here.",
    "ES": "Tapas, flamenco, and sunny beaches abound.",
    "MX": "Famous for tacos, mariachi, and ancient pyramids.",
    "KR": "K-pop and cutting-edge tech thrive in this country.",
    "TR": "Where East meets West, with historic Istanbul.",
    "NL": "Famous for windmills, tulips, and canals.",
    "SA": "Home to Mecca and vast desert landscapes.",
    "AR": "Tango and Patagonia are iconic to this country.",
    "CH": "Renowned for chocolate, watches, and the Alps.",
    "SE": "Known for ABBA, islands, and innovation.",
    "NO": "Fjords and the Northern Lights are highlights.",
    "DK": "Famous for hygge, bicycles, and fairy tales.",
    "PL": "Known for medieval cities and hearty cuisine.",
    "PT": "Fado music and pastel de nata originated here.",
    "GR": "Ancient myths and whitewashed islands define it.",
    "EG": "The pyramids and the Nile River are iconic sights.",
    "ZA": "Safari adventures and Table Mountain await here.",
    "NG": "Known for Nollywood and vibrant culture.",
    "KE": "World-famous for wildlife safaris and savannas.",
    "TH": "Street food and tropical beaches are legendary here.",
    "VN": "Rice terraces and pho are widely loved.",
    "PH": "Made up of thousands of islands and great beaches.",
    "ID": "Bali and the world’s largest archipelago are here.",
    "MY": "A mix of rainforests, skyscrapers, and street food.",
    "SG": "A tiny country known for its cleanliness and high fines.",
    "AE": "Skyscrapers and desert luxury meet here.",
    "IL": "Jerusalem and the Dead Sea are major landmarks.",
    "IR": "Ancient Persian history and poetic heritage abound.",
    "PK": "Home to the Karakoram mountains and rich traditions.",
    "BD": "Rivers, textiles, and vibrant culture stand out.",
    "UA": "Known for sunflowers, steppes, and historic cities.",
    "CZ": "Prague’s old town and castles draw many visitors.",
    "HU": "Famous for thermal baths and the Danube River.",
    "AT": "The Alps and classical music shape its identity.",
    "CH": "Famous for chocolate, precision watches, and the Alps.",
    "SE": "Known for IKEA, ABBA, and stunning northern lights.",
    "BE": "Renowned for waffles, chocolate, and medieval towns.",
    "IE": "Lush landscapes and Celtic folklore flourish here."
}
