tips_countries = {
    "Sweden": "Visit Stockholm!",
    "Spain":"Go watch a Real Madrid game!",
    "Italy": "All roads lead to rome!",
    "Portugal": "Don't miss Porto's wine!",
    "United Kingdom": "Go see Big Ben!",
    "France":"Enjoy the Eiffel Tower!",
    "Greece":"Home of Greek mythology",
    "Japan":"The home of Anime",
    "South Korea":"Home of Korean pop",
    "India":"The Taj Mahal is a must see!",
    "United Arab Emirates":"See the mesmerizing Burj Khalifa!",
    "Turkey":"The Hagia Sophia",
    "Egypt":" The Pyramids of Giza",
    "Morocco":"Go visit Casablanca",
    "South Africa":"Go Visit Nelson mandela's home country!",
    "Kenya":"Go see the safaris just outside Nairobi",
    "United States":"Home of the empire state building",
    "Canada":"Ottawa, Toronto or Montreal many cities to pick from",
    "Brazil":"Home of Christ the redeemer statue",
    "Argentina":"Make sure to go visit Lionel Messi's home country!",
    "Finland": "This country is known for thousands of lakes and saunas.",
    "Germany": "Join Oktoberfest or visit Berlin’s historical sites.",
    "China": "Walk along the Great Wall and explore Beijing’s wonders.",
    "Russia": "Visit Red Square and the colorful Saint Basil’s Cathedral.",
    "Australia": "Dive into the Great Barrier Reef or see kangaroos up close.",
    "Mexico": "Enjoy tacos, mariachi music, and ancient Mayan pyramids.",
    "Netherlands": "See the tulips, windmills, and canals in Amsterdam.",
    "Saudi Arabia": "Experience desert landscapes and the city of Mecca.",
    "Switzerland": "Explore the Alps and taste world-famous Swiss chocolate.",
    "Norway": "See the fjords and Northern Lights in this stunning country.",
    "Denmark": "Cycle around Copenhagen and experience hygge culture.",
    "Poland": "Explore medieval cities like Kraków and hearty local cuisine.",
    "Thailand": "Try incredible street food and relax on tropical beaches.",
    "Vietnam": "Cruise Ha Long Bay and enjoy a bowl of pho.",
    "Philippines": "Discover thousands of islands with crystal-clear waters.",
    "Indonesia": "Relax in Bali and explore the world's largest archipelago.",
    "Malaysia": "Climb Petronas Towers and enjoy delicious street food.",
    "Singapore": "A clean and modern city-state with world-class attractions.",
    "Israel": "Walk through Jerusalem and float in the Dead Sea.",
    "Iran": "Discover ancient Persian architecture and poetic heritage.",
    "Pakistan": "Admire the mighty Karakoram mountains.",
    "Bangladesh": "Visit the rivers, markets, and rich textile culture.",
    "Ukraine": "Explore historic Kyiv and sunflower-covered fields.",
    "Czech Republic": "Visit Prague’s old town and fairytale castles.",
    "Hungary": "Relax in Budapest’s thermal baths by the Danube.",
    "Austria": "Enjoy classical music and the beautiful Alps.",
    "Belgium": "Taste waffles, chocolate, and medieval charm.",
    "Ireland": "Discover green hills and ancient Celtic folklore.",
    "Nigeria": "Experience Nollywood and vibrant African culture."
}
