tips_countries = {
    "SE": {"name": "Sweden", "clue": "Visit Stockholm!"},
    "ES": {"name": "Spain", "clue": "Go watch a Real Madrid game!"},
    "IT": {"name": "Italy", "clue": "All roads lead to Rome!"},
    "PT": {"name": "Portugal", "clue": "Don't miss Porto's wine!"},
    "GB": {"name": "United Kingdom", "clue": "Go see Big Ben!"},
    "FR": {"name": "France", "clue": "Enjoy the Eiffel Tower!"},
    "GR": {"name": "Greece", "clue": "Home of Greek mythology"},
    "JP": {"name": "Japan", "clue": "The home of Anime"},
    "KR": {"name": "South Korea", "clue": "Home of Korean pop"},
    "IN": {"name": "India", "clue": "The Taj Mahal is a must see!"},
    "AE": {"name": "United Arab Emirates", "clue": "See the mesmerizing Burj Khalifa!"},
    "TR": {"name": "Turkey", "clue": "The Hagia Sophia"},
    "EG": {"name": "Egypt", "clue": "The Pyramids of Giza"},
    "MA": {"name": "Morocco", "clue": "Go visit Casablanca"},
    "ZA": {"name": "South Africa", "clue": "Go Visit Nelson Mandela's home country!"},
    "KE": {"name": "Kenya", "clue": "Go see the safaris just outside Nairobi"},
    "US": {"name": "United States", "clue": "Home of the Empire State Building"},
    "CA": {"name": "Canada", "clue": "Ottawa, Toronto or Montreal many cities to pick from"},
    "BR": {"name": "Brazil", "clue": "Home of Christ the Redeemer statue"},
    "AR": {"name": "Argentina", "clue": "Make sure to go visit Lionel Messi's home country!"},
    "FI": {"name": "Finland", "clue": "This country is known for thousands of lakes and saunas."},
    "DE": {"name": "Germany", "clue": "Join Oktoberfest or visit Berlin’s historical sites."},
    "CN": {"name": "China", "clue": "Walk along the Great Wall and explore Beijing’s wonders."},
    "RU": {"name": "Russia", "clue": "Visit Red Square and the colorful Saint Basil’s Cathedral."},
    "AU": {"name": "Australia", "clue": "Dive into the Great Barrier Reef or see kangaroos up close."},
    "MX": {"name": "Mexico", "clue": "Enjoy tacos, mariachi music, and ancient Mayan pyramids."},
    "NL": {"name": "Netherlands", "clue": "See the tulips, windmills, and canals in Amsterdam."},
    "SA": {"name": "Saudi Arabia", "clue": "Experience desert landscapes and the city of Mecca."},
    "CH": {"name": "Switzerland", "clue": "Explore the Alps and taste world-famous Swiss chocolate."},
    "NO": {"name": "Norway", "clue": "See the fjords and Northern Lights in this stunning country."},
    "DK": {"name": "Denmark", "clue": "Cycle around Copenhagen and experience hygge culture."},
    "PL": {"name": "Poland", "clue": "Explore medieval cities like Kraków and hearty local cuisine."},
    "TH": {"name": "Thailand", "clue": "Try incredible street food and relax on tropical beaches."},
    "VN": {"name": "Vietnam", "clue": "Cruise Ha Long Bay and enjoy a bowl of pho."},
    "PH": {"name": "Philippines", "clue": "Discover thousands of islands with crystal-clear waters."},
    "ID": {"name": "Indonesia", "clue": "Relax in Bali and explore the world's largest archipelago."},
    "MY": {"name": "Malaysia", "clue": "Climb Petronas Towers and enjoy delicious street food."},
    "SG": {"name": "Singapore", "clue": "A clean and modern city-state with high fines."},
    "IL": {"name": "Israel", "clue": "Walk through Jerusalem and float in the Dead Sea."},
    "IR": {"name": "Iran", "clue": "Discover ancient Persian architecture and poetic heritage."},
    "PK": {"name": "Pakistan", "clue": "Admire the mighty Karakoram mountains."},
    "BD": {"name": "Bangladesh", "clue": "Visit the rivers, markets, and rich textile culture."},
    "UA": {"name": "Ukraine", "clue": "Explore historic Kyiv and sunflower-covered fields."},
    "CZ": {"name": "Czech Republic", "clue": "Visit Prague’s old town and fairytale castles."},
    "HU": {"name": "Hungary", "clue": "Relax in Budapest’s thermal baths by the Danube."},
    "AT": {"name": "Austria", "clue": "Enjoy classical music and the beautiful Alps."},
    "BE": {"name": "Belgium", "clue": "Taste waffles, chocolate, and medieval charm."},
    "IE": {"name": "Ireland", "clue": "Discover green hills and ancient Celtic folklore."},
    "NG": {"name": "Nigeria", "clue": "Experience Nollywood and vibrant African culture."}
}